version: "3.4"

services:
  backendts:
    image: backendts
    network_mode: bridge
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGO_HOST: 172.17.0.2
      MONGO_PORT: 27017
    ports:
      - 8081:8081
